CORD_PATH: /scratch/ik3g20/data/cordv2/
IMG_WIDTH: 256
IMG_HEIGHT: 256
CHANNELS: 3
MAX_LABELS: 66
BATCH: 64
EPOCHS: 15
L_RATE: 0.001
CONF_LOSS_WEIGHT: 1
BBOX_LOSS_WEIGHT: 10
NUM_LABELS: 2
SAVE_DIR: checkpoints
SAVE_ENTRY: 10
SAVE_PATH_CHECKPOINT: /scratch/ik3g20/Saved_Models/IP/FRCNN_cordv2_E50_256-256_B64/
SAVE_PATH_BEST: /scratch/ik3g20/Saved_Models/IP/FRCNN_cordv2_E50_256-256_B64/Best_Model/
POS_ANCHOR_THRESH: 0.7
NEG_ANCHOR_THRESH: 0.3
ANCHOR_RATIO: 0.5
ANCHOR_SCALES: [4,8,16]
ANCHOR_RATIOS: [0.5,1,2]
STRIDE: 1
CLASSES: [menu.price]