CORD_PATH: naver-clova-ix/cord-v2
IMG_WIDTH: 512
IMG_HEIGHT: 512
CHANNELS: 3
MAX_LABELS: 22
BATCH: 64
EPOCHS: 1000
L_RATE: 0.0001
POS_WEIGHT: 0.2
NEG_WEIGHT: 0
CONF_LOSS_WEIGHT: 1
BBOX_LOSS_WEIGHT: 10
NUM_LABELS: 2
SAVE_DIR: checkpoints
SAVE_ENTRY: 10
SAVE_PATH: ./Saved_Models/model_1000_64_LR_0001_V1.pt
