PASCAL_TRAIN_IMG_PATH: ./Data/VOC2007_TRAIN/JPEGImages/
PASCAL_TRAIN_ANN_PATH: ./Data/VOC2007_TRAIN/Annotations/
PASCAL_TEST_IMG_PATH: ./Data/VOC2007_TEST/JPEGImages/
PASCAL_TEST_ANN_PATH: ./Data/VOC2007_TEST/Annotations/
IMG_WIDTH: 256
IMG_HEIGHT: 256
CHANNELS: 3
MAX_LABELS: 42
BATCH: 64
EPOCHS: 50
L_RATE: 0.001
CONF_LOSS_WEIGHT: 1
BBOX_LOSS_WEIGHT: 10
NUM_LABELS: 2
SAVE_DIR: checkpoints
SAVE_ENTRY: 10
SAVE_PATH_CHECKPOINT: ./Saved_Models/FRCNN_E50_256-256_B64/
SAVE_PATH_BEST: ./Saved_Models/FRCNN_E50_256-256_B64/Best_Model/
POS_ANCHOR_THRESH: 0.7
NEG_ANCHOR_THRESH: 0.3
ANCHOR_RATIO: 0.5
ANCHOR_SCALES: [2,4,8]
ANCHOR_RATIOS: [0.5,1,2]
STRIDE: 1
