#Model
BACKBONE: vgg16
BACKBONE_OUT_CHANNELS: 512
FEAT_SCALAR: 16
MIN_SAMPLES: 256
NUM_CLASSES: -1

#Image setting
IMG_WIDTH: 256
IMG_HEIGHT: 256
CHANNELS: 3

#Epochs and batches
EPOCHS: 20
VAL_EPOCH: 4
SAVE_ENTRY: 10
BATCH: 16
VAL_BATCH: 8

#Optimizer
L_RATE: 0.001
MOMENTUM: 0.9
W_DECAY: 0.0005

#Scheduler
STEP_SIZE: 3
GAMMA: 0.1

#RPN WEIGHTS
CONF_LOSS_WEIGHT: 1
BBOX_LOSS_WEIGHT: 10

#Base Save Dir
SAVE_DIR: checkpoints


#Anchor and Proposal Generation
POS_ANCHOR_THRESH: 0.7
NEG_ANCHOR_THRESH: 0.3
ANCHOR_RATIO: 0.5
ANCHOR_SCALES: [8,16,32]
ANCHOR_RATIOS: [0.5,1,2]
STRIDE: 16 #Stride for VGG16 model

#ROI Network
ROI_HEIGHT: 7
ROI_WIDTH: 7