#Dataset and split
DATASET: cordv2
SPLIT: train
NUM_CLASSES: 2

IMG_WIDTH: 512
IMG_HEIGHT: 512

#Epoch and Batch
BATCH: 4
VAL_BATCH: 1
EPOCHS: 20
VAL_EPOCH: 1
SAVE_ENTRY: 55
LOG_ENTRY: 1

#Optimizer
L_RATE: 0.001

#Scheduler
STEP_SIZE: 12
GAMMA: 0.1


#Save paths
SAVE_PATH_CHECKPOINT: ./Saved_Models/cordv2_E50_B4/
SAVE_PATH_BEST: ./Saved_Models/cordv2_E50_B4/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [8,16,32]

#Train
NUM_WORKERS: 0
