#Dataset and split
DATASET: cordv2
SPLIT: train
NUM_CLASSES: 30

#Epoch and Batch
BATCH: 16
VAL_BATCH: 8
EPOCHS: 100
VAL_EPOCH: 10
SAVE_ENTRY: 10

#Scheduler
STEP_SIZE: 10
GAMMA: 0.1


#Save paths
SAVE_PATH_CHECKPOINT: ./scratch/ik3g20/Saved_Models/IP/FRCNN_cordv2_E50_256-256_B64/
SAVE_PATH_BEST: ./scratch/ik3g20/Saved_Models/IP/FRCNN_cordv2_E50_256-256_B64/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [4,8,16]

