#Dataset and split
DATASET: cordv2
SPLIT: train
NUM_CLASSES: 2
CLASS_TYPE: all

MIN_SIZE: 400
MAX_SIZE: 800
TRANSFORMS: [totensor]

#Epoch and Batch
BATCH: 1
VAL_BATCH: 1
EPOCHS: 40
VAL_EPOCH: 2
SAVE_ENTRY: 55
LOG_ENTRY: 2

#Optimizer
L_RATE: 0.001

#Scheduler
STEP_SIZE: 10
GAMMA: 0.1


#Save paths
SAVE_PATH_CHECKPOINT: ./Saved_Models/cordv2_all_E40_B1_lr0.001/
SAVE_PATH_BEST: ./Saved_Models/cordv2_all_E40_B1_lr0.001/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [8,16,32]

#Train
NUM_WORKERS: 0
