#Dataset and split
DATASET: cordv2
CORD_V2_PATH: /scratch/ik3g20/data/cordv2/
SPLIT: train
NUM_CLASSES: 2

IMG_WIDTH: 512
IMG_HEIGHT: 512

#Epoch and Batch
BATCH: 4
VAL_BATCH: 2
EPOCHS: 100
VAL_EPOCH: 1
SAVE_ENTRY: 10
LOG_ENTRY: 1

#Optimizer
L_RATE: 0.005

#Scheduler
STEP_SIZE: 30
GAMMA: 0.1


#Save paths
SAVE_PATH_CHECKPOINT: /scratch/ik3g20/Saved_Models/cordv2_E100_B4/
SAVE_PATH_BEST: /scratch/ik3g20/Saved_Models/cordv2_E100_B4/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [4,8,16,32]

#Train
NUM_WORKERS: 2
