#Dataset and split
DATASET: cordv2
SPLIT: train
NUM_CLASSES: 30

IMG_WIDTH: 512
IMG_HEIGHT: 512

#Epoch and Batch
BATCH: 1
VAL_BATCH: 1
EPOCHS: 18
VAL_EPOCH: 1
SAVE_ENTRY: 5
LOG_ENTRY: 1

#Optimizer
L_RATE: 0.001

#Scheduler
STEP_SIZE: 3
GAMMA: 0.1


#Save paths
SAVE_PATH_CHECKPOINT: ./Saved_Models/IP/FRCNN_cordv2_E18_B1/
SAVE_PATH_BEST: ./Saved_Models/IP/FRCNN_cordv2_E18_B1/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [4,8,16,32]

