#Dataset and split
DATASET: cordv2
SPLIT: train
NUM_CLASSES: 2

IMG_WIDTH: 512
IMG_HEIGHT: 512

#Epoch and Batch
BATCH: 1
VAL_BATCH: 1
EPOCHS: 5
VAL_EPOCH: 1
SAVE_ENTRY: 100
LOG_ENTRY: 1

#Optimizer
L_RATE: 0.001

#Scheduler
STEP_SIZE: 1
GAMMA: 0.1


#Save paths
SAVE_PATH_CHECKPOINT: ./Saved_Models/custom_sample/
SAVE_PATH_BEST: ./Saved_Models/custom_sample/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [8,16,32]

#Train
NUM_WORKERS: 0
DDP: False
PAD: True
