#Dataset and split
DATASET: voc2007
SPLIT: train
NUM_CLASSES: 2
CLASS_TYPE: all

MIN_SIZE: 800
MAX_SIZE: 1000
TRANSFORMS: [totensor]

#Epoch and Batch
BATCH: 1
VAL_BATCH: 1
EPOCHS: 20
VAL_EPOCH: 2
SAVE_ENTRY: 10
LOG_ENTRY: 2

#Optimizer
L_RATE: 0.001

#Scheduler
STEP_SIZE: 10
GAMMA: 0.9


#Save paths
SAVE_PATH_CHECKPOINT: ./Saved_Models/custom_voc2007_E20_lr0.001/
SAVE_PATH_BEST: ./Saved_Models/custom_voc2007_E20_lr0.001/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [128,256,512]

#Train
NUM_WORKERS: 0
