#Dataset and split
DATASET: voc2007
SPLIT: train
NUM_CLASSES: 21
CLASS_TYPE: all 

#Batch and epochs
BATCH: 1
VAL_BATCH: 1
EPOCHS: 6
SAVE_ENTRY: 2
LOG_ENTRY: 2
VAL_EPOCH: 2

#Save paths
SAVE_PATH_CHECKPOINT: ./Saved_Models/custom_voc_cfg1/
SAVE_PATH_BEST: ./Saved_Models/custom_voc_cfg1/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [128,256,512]

#Optimizer
L_RATE: 0.001

#Scheduler
STEP_SIZE: 5
GAMMA: 0.1


