#Dataset and split
DATASET: voc2007
SPLIT: train

#Batch and epochs
BATCH: 16
VAL_BATCH: 8
EPOCHS: 50
SAVE_ENTRY: 10

#Save paths
SAVE_PATH_CHECKPOINT: /scratch/ik3g20/Saved_Models/IP/FRCNN_E50_256-256_B64/
SAVE_PATH_BEST: /scratch/ik3g20/Saved_Models/IP/FRCNN_E50_256-256_B64/Best_Model/

#Anchor and proposal generation
ANCHOR_SCALES: [8,16,32]
